In [4]:
import pandas as pd

marketing_end_df = pd.read_csv("marketing_end_df.csv")
# marketing_end_df.drop("Unnamed: 0", axis=1, inplace=True)
marketing_retail_df = pd.read_csv("marketing_retail_df.csv")
# marketing_retail_df.drop("Unnamed: 0", axis=1, inplace=True)
marketing_cost_df = pd.read_csv("marketing_costs_df.csv")
marketing_cost_df.drop("Unnamed: 0", axis=1, inplace=True)
charecteristics_df = pd.read_csv("charecteristics_df.csv")
charecteristics_df.drop("Unnamed: 0", axis=1, inplace=True)
additional_df = pd.read_csv("additional_df.csv")
additional_df.drop("Unnamed: 0", axis=1, inplace=True)
demand_df = pd.read_csv("demand_df.csv")
demand_df.drop("Unnamed: 0", axis=1, inplace=True)
first_time_df = pd.read_csv("first_time_df.csv")
first_time_df.drop("Unnamed: 0", axis=1, inplace=True)
rate_of_coverage_df = pd.read_csv("rate_of_coverage_df.csv")
rate_of_coverage_df.drop("Unnamed: 0", axis=1, inplace=True)
rate_of_coverage_segment_df = pd.read_csv("rate_of_coverage_segment_df.csv")
rate_of_coverage_segment_df.drop("Unnamed: 0", axis=1, inplace=True)
segment_size_df = pd.read_csv("segments_size_df.csv")
segment_size_df.drop("Unnamed: 0", axis=1, inplace=True)
total_purchases_df = pd.read_csv("total_purchase_df.csv")
total_purchases_df.drop("Unnamed: 0", axis=1, inplace=True)
market_share_df = pd.read_csv("market_share_df.csv")
market_share_df.drop("Unnamed: 0", axis=1, inplace=True)
sales_df = pd.read_csv("sales_df.csv")

In [5]:
n_df=pd.melt(
    marketing_end_df,
    id_vars=["Period", "Company"],
    value_vars=["1", "2", "3", "4", "5", "6"],
)
n_df.rename(columns={"variable": "Model", "value": "Marketing End"}, inplace=True)
n_df

    Period Company Model Marketing End
0       17    Digi     1             0
1       17  Profit     1             0
2       17  Primus     1            50
3       17    Best     1             0
4       17   Mikro     1           500
5       17    Digi     2           400
6       17  Profit     2           500
7       17  Primus     2          1000
8       17    Best     2           800
9       17   Mikro     2          1000
10      17    Digi     3           600
11      17  Profit     3           500
12      17  Primus     3           600
13      17    Best     3           800
14      17   Mikro     3           600
15      17    Digi     4             O
16      17  Profit     4           600
17      17  Primus     4           900
18      17    Best     4           700
19      17   Mikro     4             O
20      17    Digi     5             0
21      17  Profit     5             O
22      17  Primus     5             O
23      17    Best     5           400
24      17   Mikro     5             0
25      17    Digi     6             0
26      17  Profit     6             0
27      17  Primus     6             0
28      17    Best     6             O
29      17   Mikro     6             0

In [6]:
n2_df=pd.melt(
    marketing_retail_df,
    id_vars=["Period", "Company"],
    value_vars=["1", "2", "3", "4", "5", "6"],
)
n2_df.rename(columns={"variable": "Model", "value": "Marketing Retail"}, inplace=True)

n_df=n_df.merge(n2_df, on=["Period", "Company", "Model"], how="left")
n_df

    Period Company Model Marketing End  Marketing Retail
0       17    Digi     1             0               0.0
1       17  Profit     1             0               0.0
2       17  Primus     1            50              50.0
3       17    Best     1             0               0.0
4       17   Mikro     1           500             100.0
5       17    Digi     2           400             700.0
6       17  Profit     2           500             500.0
7       17  Primus     2          1000            1000.0
8       17    Best     2           800             800.0
9       17   Mikro     2          1000             500.0
10      17    Digi     3           600             900.0
11      17  Profit     3           500             500.0
12      17  Primus     3           600             500.0
13      17    Best     3           800             800.0
14      17   Mikro     3           600            1000.0
15      17    Digi     4             O               0.0
16      17  Profit     4           600             600.0
17      17  Primus     4           900             900.0
18      17    Best     4           700             700.0
19      17   Mikro     4             O               0.0
20      17    Digi     5             0               0.0
21      17  Profit     5             O               0.0
22      17  Primus     5             O               0.0
23      17    Best     5           400             200.0
24      17   Mikro     5             0               0.0
25      17    Digi     6             0               0.0
26      17  Profit     6             0               0.0
27      17  Primus     6             0               0.0
28      17    Best     6             O               0.0
29      17   Mikro     6             0               0.0

In [7]:
charecteristics_df["Model_Split"]=charecteristics_df["Model"].str.extract('(\d+)')
charecteristics_df.rename(columns={"Model":"Model Name","Model_Split": "Model"}, inplace=True)
charecteristics_df

,Model Name,Company,Durability,Design,Connectivity,Maintenance,Accessories,Period,Model
0,Digi1,Digi,"0,3","1,0","0,3","0,3","0,3",17,1
1,Digi2,Digi,"2,8","2,8","2,8","1,9","1,9",17,2
2,Digi3,Digi,"1,0","2,0","2,0","1,0","2,0",17,3
3,Profit1,Profit,"0,3","0,3","0,3","0,7","0,3",17,1
4,Profit2,Profit,"1,9","0,9","1,9","0,9","1,9",17,2
5,Profit3,Profit,"1,0","3,0","1,0","2,0","3,0",17,3
6,Profit4,Profit,"1,0","1,0","2,0","1,0","1,0",17,4
7,Primus1,Primus,"0,3","0,3","0,3","0,7","0,3",17,1
8,Primus2,Primus,"1,9","0,9","2,8","1,9","0,9",17,2
9,Primus3,Primus,"3,0","2,0","3,0","3,0","2,0",17,3
10,Primus4,Primus,"1,0","1,0","2,0","1,0","1,0",17,4
11,Best1,Best,"0,3","0,3","0,3","1,0","0,3",17,1
12,Best2,Best,"1,9","0,9","1,9","0,9","0,9",17,2
13,Best3,Best,"2,0","3,0","3,0","2,0","1,0",17,3
14,Best4,Best,"3,0","1,0","3,0","2,0","1,0",17,4
15,Best5,Best,"2,0","2,0","2,0","2,0","1,0",17,5
16,Mikro1,Mikro,"0,3","0,3","0,3","0,3","0,3",17,1
17,Mikro2,Mikro,"3,0","3,0","3,0","3,0","3,0",17,2
18,Mikro3,Mikro,"1,0","1,0","1,0","1,0","1,0",17,3

In [12]:
n_df=n_df.merge(charecteristics_df, on=["Model","Period","Company"], how="left")

In [ ]:
marketing_end_df.rename(columns={"Cost": "Marketing End User"}, inplace=True)

In [ ]:
n_df=n_df.merge(marketing_end_df, on=["Period", "Company"], how="left")

In [13]:
n_df

,Period,Company,Model,Marketing End,Marketing Retail,Model Name,Durability,Design,Connectivity,Maintenance,Accessories
0,17,Digi,1,0,0.0,Digi1,"0,3","1,0","0,3","0,3","0,3"
1,17,Profit,1,0,0.0,Profit1,"0,3","0,3","0,3","0,7","0,3"
2,17,Primus,1,50,50.0,Primus1,"0,3","0,3","0,3","0,7","0,3"
3,17,Best,1,0,0.0,Best1,"0,3","0,3","0,3","1,0","0,3"
4,17,Mikro,1,500,100.0,Mikro1,"0,3","0,3","0,3","0,3","0,3"
5,17,Digi,2,400,700.0,Digi2,"2,8","2,8","2,8","1,9","1,9"
6,17,Profit,2,500,500.0,Profit2,"1,9","0,9","1,9","0,9","1,9"
7,17,Primus,2,1000,1000.0,Primus2,"1,9","0,9","2,8","1,9","0,9"
8,17,Best,2,800,800.0,Best2,"1,9","0,9","1,9","0,9","0,9"
9,17,Mikro,2,1000,500.0,Mikro2,"3,0","3,0","3,0","3,0","3,0"
10,17,Digi,3,600,900.0,Digi3,"1,0","2,0","2,0","1,0","2,0"
11,17,Profit,3,500,500.0,Profit3,"1,0","3,0","1,0","2,0","3,0"
12,17,Primus,3,600,500.0,Primus3,"3,0","2,0","3,0","3,0","2,0"
13,17,Best,3,800,800.0,Best3,"2,0","3,0","3,0","2,0","1,0"
14,17,Mikro,3,600,1000.0,Mikro3,"1,0","1,0","1,0","1,0","1,0"
15,17,Digi,4,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Profit,4,600,600.0,Profit4,"1,0","1,0","2,0","1,0","1,0"
17,17,Primus,4,900,900.0,Primus4,"1,0","1,0","2,0","1,0","1,0"
18,17,Best,4,700,700.0,Best4,"3,0","1,0","3,0","2,0","1,0"
19,17,Mikro,4,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN
20,17,Digi,5,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
21,17,Profit,5,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN
22,17,Primus,5,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN
23,17,Best,5,400,200.0,Best5,"2,0","2,0","2,0","2,0","1,0"
24,17,Mikro,5,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
25,17,Digi,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
26,17,Profit,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
27,17,Primus,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
28,17,Best,6,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN
29,17,Mikro,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
marketing_retail_df.rename(columns={"Cost": "Marketing Retailer"}, inplace=True)
n_df = n_df.merge(marketing_retail_df, on=["Period", "Company"], how="left")
n_df

,Period,Company,Model,Marketing End,Marketing Retail,Unnamed: 0_x,1_x,2_x,3_x,4_x,...,6_x,sum_x,Unnamed: 0_y,1_y,2_y,3_y,4_y,5_y,6_y,sum_y
0,17,Digi,1,0,0.0,0,0,400,600,O,...,0,1000,0,0.0,700.0,900.0,0.0,0.0,0.0,1600.0
1,17,Profit,1,0,0.0,1,0,500,500,600,...,0,1600,1,0.0,500.0,500.0,600.0,0.0,0.0,1600.0
2,17,Primus,1,50,50.0,2,50,1000,600,900,...,0,2550,2,50.0,1000.0,500.0,900.0,0.0,0.0,2450.0
3,17,Best,1,0,0.0,3,0,800,800,700,...,O,2700,3,0.0,800.0,800.0,700.0,200.0,0.0,2500.0
4,17,Mikro,1,500,100.0,4,500,1000,600,O,...,0,2100,4,100.0,500.0,1000.0,0.0,0.0,0.0,1600.0
5,17,Digi,2,400,700.0,0,0,400,600,O,...,0,1000,0,0.0,700.0,900.0,0.0,0.0,0.0,1600.0
6,17,Profit,2,500,500.0,1,0,500,500,600,...,0,1600,1,0.0,500.0,500.0,600.0,0.0,0.0,1600.0
7,17,Primus,2,1000,1000.0,2,50,1000,600,900,...,0,2550,2,50.0,1000.0,500.0,900.0,0.0,0.0,2450.0
8,17,Best,2,800,800.0,3,0,800,800,700,...,O,2700,3,0.0,800.0,800.0,700.0,200.0,0.0,2500.0
9,17,Mikro,2,1000,500.0,4,500,1000,600,O,...,0,2100,4,100.0,500.0,1000.0,0.0,0.0,0.0,1600.0
10,17,Digi,3,600,900.0,0,0,400,600,O,...,0,1000,0,0.0,700.0,900.0,0.0,0.0,0.0,1600.0
11,17,Profit,3,500,500.0,1,0,500,500,600,...,0,1600,1,0.0,500.0,500.0,600.0,0.0,0.0,1600.0
12,17,Primus,3,600,500.0,2,50,1000,600,900,...,0,2550,2,50.0,1000.0,500.0,900.0,0.0,0.0,2450.0
13,17,Best,3,800,800.0,3,0,800,800,700,...,O,2700,3,0.0,800.0,800.0,700.0,200.0,0.0,2500.0
14,17,Mikro,3,600,1000.0,4,500,1000,600,O,...,0,2100,4,100.0,500.0,1000.0,0.0,0.0,0.0,1600.0
15,17,Digi,4,O,0.0,0,0,400,600,O,...,0,1000,0,0.0,700.0,900.0,0.0,0.0,0.0,1600.0
16,17,Profit,4,600,600.0,1,0,500,500,600,...,0,1600,1,0.0,500.0,500.0,600.0,0.0,0.0,1600.0
17,17,Primus,4,900,900.0,2,50,1000,600,900,...,0,2550,2,50.0,1000.0,500.0,900.0,0.0,0.0,2450.0
18,17,Best,4,700,700.0,3,0,800,800,700,...,O,2700,3,0.0,800.0,800.0,700.0,200.0,0.0,2500.0
19,17,Mikro,4,O,0.0,4,500,1000,600,O,...,0,2100,4,100.0,500.0,1000.0,0.0,0.0,0.0,1600.0
20,17,Digi,5,0,0.0,0,0,400,600,O,...,0,1000,0,0.0,700.0,900.0,0.0,0.0,0.0,1600.0
21,17,Profit,5,O,0.0,1,0,500,500,600,...,0,1600,1,0.0,500.0,500.0,600.0,0.0,0.0,1600.0
22,17,Primus,5,O,0.0,2,50,1000,600,900,...,0,2550,2,50.0,1000.0,500.0,900.0,0.0,0.0,2450.0
23,17,Best,5,400,200.0,3,0,800,800,700,...,O,2700,3,0.0,800.0,800.0,700.0,200.0,0.0,2500.0
24,17,Mikro,5,0,0.0,4,500,1000,600,O,...,0,2100,4,100.0,500.0,1000.0,0.0,0.0,0.0,1600.0
25,17,Digi,6,0,0.0,0,0,400,600,O,...,0,1000,0,0.0,700.0,900.0,0.0,0.0,0.0,1600.0
26,17,Profit,6,0,0.0,1,0,500,500,600,...,0,1600,1,0.0,500.0,500.0,600.0,0.0,0.0,1600.0
27,17,Primus,6,0,0.0,2,50,1000,600,900,...,0,2550,2,50.0,1000.0,500.0,900.0,0.0,0.0,2450.0
28,17,Best,6,O,0.0,3,0,800,800,700,...,O,2700,3,0.0,800.0,800.0,700.0,200.0,0.0,2500.0
29,17,Mikro,6,0,0.0,4,500,1000,600,O,...,0,2100,4,100.0,500.0,1000.0,0.0,0.0,0.0,1600.0

In [ ]:
n_df = n_df.merge(charecteristics_df, on=["Period", "Model","Company"], how="left")
n_df

,Period,Company,Model,Marketing End,Marketing Retail,Unnamed: 0_x,1_x,2_x,3_x,4_x,...,4_y,5_y,6_y,sum_y,Model Name,Durability,Design,Connectivity,Maintenance,Accessories
0,17,Digi,1,0,0.0,0,0,400,600,O,...,0.0,0.0,0.0,1600.0,Digi1,"0,3","1,0","0,3","0,3","0,3"
1,17,Profit,1,0,0.0,1,0,500,500,600,...,600.0,0.0,0.0,1600.0,Profit1,"0,3","0,3","0,3","0,7","0,3"
2,17,Primus,1,50,50.0,2,50,1000,600,900,...,900.0,0.0,0.0,2450.0,Primus1,"0,3","0,3","0,3","0,7","0,3"
3,17,Best,1,0,0.0,3,0,800,800,700,...,700.0,200.0,0.0,2500.0,Best1,"0,3","0,3","0,3","1,0","0,3"
4,17,Mikro,1,500,100.0,4,500,1000,600,O,...,0.0,0.0,0.0,1600.0,Mikro1,"0,3","0,3","0,3","0,3","0,3"
5,17,Digi,2,400,700.0,0,0,400,600,O,...,0.0,0.0,0.0,1600.0,Digi2,"2,8","2,8","2,8","1,9","1,9"
6,17,Profit,2,500,500.0,1,0,500,500,600,...,600.0,0.0,0.0,1600.0,Profit2,"1,9","0,9","1,9","0,9","1,9"
7,17,Primus,2,1000,1000.0,2,50,1000,600,900,...,900.0,0.0,0.0,2450.0,Primus2,"1,9","0,9","2,8","1,9","0,9"
8,17,Best,2,800,800.0,3,0,800,800,700,...,700.0,200.0,0.0,2500.0,Best2,"1,9","0,9","1,9","0,9","0,9"
9,17,Mikro,2,1000,500.0,4,500,1000,600,O,...,0.0,0.0,0.0,1600.0,Mikro2,"3,0","3,0","3,0","3,0","3,0"
10,17,Digi,3,600,900.0,0,0,400,600,O,...,0.0,0.0,0.0,1600.0,Digi3,"1,0","2,0","2,0","1,0","2,0"
11,17,Profit,3,500,500.0,1,0,500,500,600,...,600.0,0.0,0.0,1600.0,Profit3,"1,0","3,0","1,0","2,0","3,0"
12,17,Primus,3,600,500.0,2,50,1000,600,900,...,900.0,0.0,0.0,2450.0,Primus3,"3,0","2,0","3,0","3,0","2,0"
13,17,Best,3,800,800.0,3,0,800,800,700,...,700.0,200.0,0.0,2500.0,Best3,"2,0","3,0","3,0","2,0","1,0"
14,17,Mikro,3,600,1000.0,4,500,1000,600,O,...,0.0,0.0,0.0,1600.0,Mikro3,"1,0","1,0","1,0","1,0","1,0"
15,17,Digi,4,O,0.0,0,0,400,600,O,...,0.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Profit,4,600,600.0,1,0,500,500,600,...,600.0,0.0,0.0,1600.0,Profit4,"1,0","1,0","2,0","1,0","1,0"
17,17,Primus,4,900,900.0,2,50,1000,600,900,...,900.0,0.0,0.0,2450.0,Primus4,"1,0","1,0","2,0","1,0","1,0"
18,17,Best,4,700,700.0,3,0,800,800,700,...,700.0,200.0,0.0,2500.0,Best4,"3,0","1,0","3,0","2,0","1,0"
19,17,Mikro,4,O,0.0,4,500,1000,600,O,...,0.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN
20,17,Digi,5,0,0.0,0,0,400,600,O,...,0.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN
21,17,Profit,5,O,0.0,1,0,500,500,600,...,600.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN
22,17,Primus,5,O,0.0,2,50,1000,600,900,...,900.0,0.0,0.0,2450.0,NaN,NaN,NaN,NaN,NaN,NaN
23,17,Best,5,400,200.0,3,0,800,800,700,...,700.0,200.0,0.0,2500.0,Best5,"2,0","2,0","2,0","2,0","1,0"
24,17,Mikro,5,0,0.0,4,500,1000,600,O,...,0.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN
25,17,Digi,6,0,0.0,0,0,400,600,O,...,0.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN
26,17,Profit,6,0,0.0,1,0,500,500,600,...,600.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN
27,17,Primus,6,0,0.0,2,50,1000,600,900,...,900.0,0.0,0.0,2450.0,NaN,NaN,NaN,NaN,NaN,NaN
28,17,Best,6,O,0.0,3,0,800,800,700,...,700.0,200.0,0.0,2500.0,NaN,NaN,NaN,NaN,NaN,NaN
29,17,Mikro,6,0,0.0,4,500,1000,600,O,...,0.0,0.0,0.0,1600.0,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
demand_df["Model_Split"]=demand_df["Model"].str.extract('(\d+)')
demand_df.drop("Model", axis=1, inplace=True)
demand_df.rename(columns={"Model_Split": "Model"}, inplace=True)
n_df = n_df.merge(demand_df, on=["Period", "Model","Company"], how="left")
n_df

,Period,Company,Model,Marketing End,Marketing Retail,Model Name,Durability,Design,Connectivity,Maintenance,Accessories,Small income young families,Small income middle-aged families,Small income elderly families,Average income young families,Average income middle-aged families,Average income elderly families,Large income families
0,17,Digi,1,0,0.0,Digi1,"0,3","1,0","0,3","0,3","0,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,17,Profit,1,0,0.0,Profit1,"0,3","0,3","0,3","0,7","0,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,17,Primus,1,50,50.0,Primus1,"0,3","0,3","0,3","0,7","0,3",0.0,1.0,8.0,0.0,0.0,2.0,0.0
3,17,Best,1,0,0.0,Best1,"0,3","0,3","0,3","1,0","0,3",0.0,0.0,1.0,0.0,0.0,1.0,1.0
4,17,Mikro,1,500,100.0,Mikro1,"0,3","0,3","0,3","0,3","0,3",1.0,1.0,3.0,0.0,1.0,2.0,0.0
5,17,Digi,2,400,700.0,Digi2,"2,8","2,8","2,8","1,9","1,9",5.0,2.0,1.0,6.0,3.0,1.0,8.0
6,17,Profit,2,500,500.0,Profit2,"1,9","0,9","1,9","0,9","1,9",15.0,17.0,18.0,12.0,16.0,18.0,10.0
7,17,Primus,2,1000,1000.0,Primus2,"1,9","0,9","2,8","1,9","0,9",23.0,33.0,31.0,21.0,32.0,33.0,17.0
8,17,Best,2,800,800.0,Best2,"1,9","0,9","1,9","0,9","0,9",11.0,14.0,14.0,8.0,13.0,14.0,7.0
9,17,Mikro,2,1000,500.0,Mikro2,"3,0","3,0","3,0","3,0","3,0",12.0,4.0,1.0,16.0,6.0,2.0,21.0
10,17,Digi,3,600,900.0,Digi3,"1,0","2,0","2,0","1,0","2,0",8.0,8.0,7.0,7.0,7.0,8.0,6.0
11,17,Profit,3,500,500.0,Profit3,"1,0","3,0","1,0","2,0","3,0",4.0,1.0,0.0,4.0,2.0,1.0,5.0
12,17,Primus,3,600,500.0,Primus3,"3,0","2,0","3,0","3,0","2,0",6.0,3.0,1.0,8.0,4.0,2.0,10.0
13,17,Best,3,800,800.0,Best3,"2,0","3,0","3,0","2,0","1,0",8.0,3.0,1.0,9.0,5.0,2.0,10.0
14,17,Mikro,3,600,1000.0,Mikro3,"1,0","1,0","1,0","1,0","1,0",0.0,1.0,1.0,0.0,0.0,1.0,0.0
15,17,Digi,4,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Profit,4,600,600.0,Profit4,"1,0","1,0","2,0","1,0","1,0",1.0,1.0,2.0,0.0,1.0,1.0,0.0
17,17,Primus,4,900,900.0,Primus4,"1,0","1,0","2,0","1,0","1,0",4.0,8.0,11.0,3.0,6.0,9.0,2.0
18,17,Best,4,700,700.0,Best4,"3,0","1,0","3,0","2,0","1,0",3.0,2.0,1.0,3.0,2.0,1.0,3.0
19,17,Mikro,4,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,17,Digi,5,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,17,Profit,5,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,17,Primus,5,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,17,Best,5,400,200.0,Best5,"2,0","2,0","2,0","2,0","1,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,17,Mikro,5,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,17,Digi,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,17,Profit,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,17,Primus,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,17,Best,6,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,17,Mikro,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
R_C =pd.melt(
    rate_of_coverage_df,
    id_vars=["Period", "Company"],
    value_vars=["1", "2", "3", "4", "5", "6"],
)
R_C

Empty DataFrame
Columns: [Period, Company, variable, value]
Index: []

In [ ]:
R_C.rename(columns={"variable": "Model","value":"Rate of Coverage"}, inplace=True)
R_C

Empty DataFrame
Columns: [Period, Company, Model, Rate of Coverage]
Index: []

In [ ]:
n_df = n_df.merge(R_C, on=["Period", "Model","Company"], how="left")
n_df

,Period,Company,Model,Marketing End,Marketing Retail,Unnamed: 0_x,1_x,2_x,3_x,4_x,...,Maintenance,Accessories,Small income young families,Small income middle-aged families,Small income elderly families,Average income young families,Average income middle-aged families,Average income elderly families,Large income families,Rate of Coverage
0,17,Digi,1,0,0.0,0,0,400,600,O,...,"0,3","0,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,17,Profit,1,0,0.0,1,0,500,500,600,...,"0,7","0,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,17,Primus,1,50,50.0,2,50,1000,600,900,...,"0,7","0,3",0.0,1.0,8.0,0.0,0.0,2.0,0.0,NaN
3,17,Best,1,0,0.0,3,0,800,800,700,...,"1,0","0,3",0.0,0.0,1.0,0.0,0.0,1.0,1.0,NaN
4,17,Mikro,1,500,100.0,4,500,1000,600,O,...,"0,3","0,3",1.0,1.0,3.0,0.0,1.0,2.0,0.0,NaN
5,17,Digi,2,400,700.0,0,0,400,600,O,...,"1,9","1,9",5.0,2.0,1.0,6.0,3.0,1.0,8.0,NaN
6,17,Profit,2,500,500.0,1,0,500,500,600,...,"0,9","1,9",15.0,17.0,18.0,12.0,16.0,18.0,10.0,NaN
7,17,Primus,2,1000,1000.0,2,50,1000,600,900,...,"1,9","0,9",23.0,33.0,31.0,21.0,32.0,33.0,17.0,NaN
8,17,Best,2,800,800.0,3,0,800,800,700,...,"0,9","0,9",11.0,14.0,14.0,8.0,13.0,14.0,7.0,NaN
9,17,Mikro,2,1000,500.0,4,500,1000,600,O,...,"3,0","3,0",12.0,4.0,1.0,16.0,6.0,2.0,21.0,NaN
10,17,Digi,3,600,900.0,0,0,400,600,O,...,"1,0","2,0",8.0,8.0,7.0,7.0,7.0,8.0,6.0,NaN
11,17,Profit,3,500,500.0,1,0,500,500,600,...,"2,0","3,0",4.0,1.0,0.0,4.0,2.0,1.0,5.0,NaN
12,17,Primus,3,600,500.0,2,50,1000,600,900,...,"3,0","2,0",6.0,3.0,1.0,8.0,4.0,2.0,10.0,NaN
13,17,Best,3,800,800.0,3,0,800,800,700,...,"2,0","1,0",8.0,3.0,1.0,9.0,5.0,2.0,10.0,NaN
14,17,Mikro,3,600,1000.0,4,500,1000,600,O,...,"1,0","1,0",0.0,1.0,1.0,0.0,0.0,1.0,0.0,NaN
15,17,Digi,4,O,0.0,0,0,400,600,O,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Profit,4,600,600.0,1,0,500,500,600,...,"1,0","1,0",1.0,1.0,2.0,0.0,1.0,1.0,0.0,NaN
17,17,Primus,4,900,900.0,2,50,1000,600,900,...,"1,0","1,0",4.0,8.0,11.0,3.0,6.0,9.0,2.0,NaN
18,17,Best,4,700,700.0,3,0,800,800,700,...,"2,0","1,0",3.0,2.0,1.0,3.0,2.0,1.0,3.0,NaN
19,17,Mikro,4,O,0.0,4,500,1000,600,O,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,17,Digi,5,0,0.0,0,0,400,600,O,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,17,Profit,5,O,0.0,1,0,500,500,600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,17,Primus,5,O,0.0,2,50,1000,600,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,17,Best,5,400,200.0,3,0,800,800,700,...,"2,0","1,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,17,Mikro,5,0,0.0,4,500,1000,600,O,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,17,Digi,6,0,0.0,0,0,400,600,O,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,17,Profit,6,0,0.0,1,0,500,500,600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,17,Primus,6,0,0.0,2,50,1000,600,900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,17,Best,6,O,0.0,3,0,800,800,700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,17,Mikro,6,0,0.0,4,500,1000,600,O,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
sales_df

      Model  Price  Period
0     Digi1      1      17
1     Digi2   3300      17
2     Digi3  2 250      17
3   Profit1      1      17
4   Profit2   2180      17
5   Profit3  2 899      17
6   Profit4   1959      17
7     Best1   1750      17
8     Best2  2 268      17
9     Best3   3150      17
10    Best4  2 877      17
11    Best5  2 598      17
12   Mikro1  1 600      17
13   Mikro2   3450      17
14   Mikro3   1950      17

In [16]:
sales_df["Model_Split"]=sales_df["Model"].str.extract('(\d+)')
sales_df["Company"]=sales_df["Model"].str.extract('([A-Za-z]+)')
sales_df.drop("Model", axis=1, inplace=True)
sales_df.rename(columns={"Model_Split": "Model"}, inplace=True)
sales_df

    Price  Period Model Company
0       1      17     1    Digi
1    3300      17     2    Digi
2   2 250      17     3    Digi
3       1      17     1  Profit
4    2180      17     2  Profit
5   2 899      17     3  Profit
6    1959      17     4  Profit
7    1750      17     1    Best
8   2 268      17     2    Best
9    3150      17     3    Best
10  2 877      17     4    Best
11  2 598      17     5    Best
12  1 600      17     1   Mikro
13   3450      17     2   Mikro
14   1950      17     3   Mikro

In [17]:
n_df = n_df.merge(sales_df, on=["Period", "Model","Company"], how="left")

n_df

,Period,Company,Model,Marketing End,Marketing Retail,Model Name,Durability,Design,Connectivity,Maintenance,Accessories,Small income young families,Small income middle-aged families,Small income elderly families,Average income young families,Average income middle-aged families,Average income elderly families,Large income families,Price
0,17,Digi,1,0,0.0,Digi1,"0,3","1,0","0,3","0,3","0,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,17,Profit,1,0,0.0,Profit1,"0,3","0,3","0,3","0,7","0,3",0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,17,Primus,1,50,50.0,Primus1,"0,3","0,3","0,3","0,7","0,3",0.0,1.0,8.0,0.0,0.0,2.0,0.0,NaN
3,17,Best,1,0,0.0,Best1,"0,3","0,3","0,3","1,0","0,3",0.0,0.0,1.0,0.0,0.0,1.0,1.0,1750
4,17,Mikro,1,500,100.0,Mikro1,"0,3","0,3","0,3","0,3","0,3",1.0,1.0,3.0,0.0,1.0,2.0,0.0,1 600
5,17,Digi,2,400,700.0,Digi2,"2,8","2,8","2,8","1,9","1,9",5.0,2.0,1.0,6.0,3.0,1.0,8.0,3300
6,17,Profit,2,500,500.0,Profit2,"1,9","0,9","1,9","0,9","1,9",15.0,17.0,18.0,12.0,16.0,18.0,10.0,2180
7,17,Primus,2,1000,1000.0,Primus2,"1,9","0,9","2,8","1,9","0,9",23.0,33.0,31.0,21.0,32.0,33.0,17.0,NaN
8,17,Best,2,800,800.0,Best2,"1,9","0,9","1,9","0,9","0,9",11.0,14.0,14.0,8.0,13.0,14.0,7.0,2 268
9,17,Mikro,2,1000,500.0,Mikro2,"3,0","3,0","3,0","3,0","3,0",12.0,4.0,1.0,16.0,6.0,2.0,21.0,3450
10,17,Digi,3,600,900.0,Digi3,"1,0","2,0","2,0","1,0","2,0",8.0,8.0,7.0,7.0,7.0,8.0,6.0,2 250
11,17,Profit,3,500,500.0,Profit3,"1,0","3,0","1,0","2,0","3,0",4.0,1.0,0.0,4.0,2.0,1.0,5.0,2 899
12,17,Primus,3,600,500.0,Primus3,"3,0","2,0","3,0","3,0","2,0",6.0,3.0,1.0,8.0,4.0,2.0,10.0,NaN
13,17,Best,3,800,800.0,Best3,"2,0","3,0","3,0","2,0","1,0",8.0,3.0,1.0,9.0,5.0,2.0,10.0,3150
14,17,Mikro,3,600,1000.0,Mikro3,"1,0","1,0","1,0","1,0","1,0",0.0,1.0,1.0,0.0,0.0,1.0,0.0,1950
15,17,Digi,4,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Profit,4,600,600.0,Profit4,"1,0","1,0","2,0","1,0","1,0",1.0,1.0,2.0,0.0,1.0,1.0,0.0,1959
17,17,Primus,4,900,900.0,Primus4,"1,0","1,0","2,0","1,0","1,0",4.0,8.0,11.0,3.0,6.0,9.0,2.0,NaN
18,17,Best,4,700,700.0,Best4,"3,0","1,0","3,0","2,0","1,0",3.0,2.0,1.0,3.0,2.0,1.0,3.0,2 877
19,17,Mikro,4,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,17,Digi,5,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,17,Profit,5,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,17,Primus,5,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,17,Best,5,400,200.0,Best5,"2,0","2,0","2,0","2,0","1,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 598
24,17,Mikro,5,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,17,Digi,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,17,Profit,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,17,Primus,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,17,Best,6,O,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,17,Mikro,6,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
n_df.to_csv("n_df.csv", index=False)